# Generated by Django 4.2.1 on 2023-05-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='article',
            name='create_date',
            field=models.DateField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название статьи'),
        ),
        migrations.AlterModelTable(
            name='article',
            table='article',
        ),
    ]
